spring:
  profiles:
    group:
      "local": "local, common"
      "prod": "prod, common"
---
spring:
  config:
    activate:
      on-profile: "common"

  grpc:
    server:
      port: 9090
      reflection:
        enabled: true

  output:
    ansi:
      enabled: always

management:
  server:
    port: 9091
  endpoint:
    health:
      show-details: always
      show-components: always

db-host: ${DB_HOST}
db-username: ${DB_USERNAME}
db-password: ${DB_PASSWORD}
redis-host: ${REDIS_HOST}
redis-port: ${REDIS_PORT}
redis-password: ${REDIS_PASSWORD}
penguin-client-id: ${PENGUIN_CLIENT_ID}
penguin-client-secret: ${PENGUIN_CLIENT_SECRET}
jwt-private-key: ${JWT_PRIVATE_KEY}
jwt-public-key: ${JWT_PUBLIC_KEY}
---
spring:
  config:
    activate:
      on-profile: "local"

logging:
  level:
    root: debug

---
spring:
  config:
    activate:
      on-profile: "prod"

logging:
  level:
    root: info
