spring:
  profiles:
    group:
      "local": "local, common"
      "prod": "prod, common"
---
spring:
  config:
    activate:
      on-profile: "common"

  grpc:
    server:
      port: 9090
      reflection:
        enabled: true

  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

management:
  server:
    port: 9091
  endpoint:
    health:
      show-details: always
      show-components: always

db-host: ${DB_HOST}
db-username: ${DB_USERNAME}
db-password: ${DB_PASSWORD}
redis-host: ${REDIS_HOST}
redis-port: ${REDIS_PORT}
redis-password: ${REDIS_PASSWORD}
---
spring:
  config:
    activate:
      on-profile: "local"

logging:
  level:
    root: debug

---
spring:
  config:
    activate:
      on-profile: "prod"

logging:
  level:
    root: info
