spring:
  profiles:
    group:
      "local": "local, common"
      "prod": "prod, common"
---
spring:
  config:
    activate:
      on-profile: "common"

  grpc:
    server:
      port: 9090
      reflection:
        enabled: true

  output:
    ansi:
      enabled: always

---
spring:
  config:
    activate:
      on-profile: "local"

logging:
  level:
    root: debug

---
spring:
  config:
    activate:
      on-profile: "prod"

logging:
  level:
    root: info
