apiVersion: apps/v1
kind: Deployment
metadata:
  name: devume-api
  namespace: devume
spec:
  selector:
    matchLabels:
      app: devume-api
  replicas: 2
  template:
    metadata:
      labels:
        app: devume-api
    spec:
      containers:
        - name: devume-api
          image: 10.105.58.187:5000/devume-api:35
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: devume-secret
          ports:
          - containerPort: 9090
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 5

