syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.penguin.api";
option java_outer_classname = "BlogProto";

service Blog {
  rpc GetBlogs (BlogRequest) returns (BlogResponse) {}
  rpc PreparePost (PreparePostRequest) returns (PreparePostResponse) {}
  rpc Validate(ValidationRequest) returns (ValidationResponse) {}
  rpc Write(WriteRequest) returns (WriteResponse) {}
}

message BlogRequest {
  int32 count = 1;
}

message BlogContent {
  string id = 1;
  string title = 2;
  string summary = 3;
  string contents = 4;
  string author = 5;
  string thumbnail = 6;
  int64 thumbs = 7;
  int64 views = 8;
}

message BlogResponse {
  repeated BlogContent blogs = 1;
}

message PreparePostRequest {
  optional int64 postId = 1;
}

message PreparePostResponse {
  optional string title = 1;
  optional string content = 2;
}

message ValidationRequest {
  string title = 1;
  string contents = 2;
}

message ValidationResponse {
  int32 status = 1;
  string message = 2;
}

message WriteRequest {
  optional int64 postId = 1;
  string title = 2;
  string contents = 3;
  string thumbnail = 4;
}

message WriteResponse {
  int64 postId = 1;
}